default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: <%= ENV['OPUS_UA_BACKEND_DEV_DATABASE_USERNAME'] %>
  password: <%= ENV['OPUS_UA_BACKEND_DEV_DATABASE_PASSWORD'] %>

development:
  <<: *default
  host: <%= ENV['OPUS_UA_BACKEND_DEV_DATABASE_HOST'] %>
  database: <%= ENV['OPUS_UA_BACKEND_DEV_DATABASE_NAME'] %>

test:
  <<: *default
  database: opus-ua-backend_test

staging:
  host: <%= ENV['OPUS_UA_BACKEND_STG_DATABASE_HOST'] %>
  adapter: postgresql
  database: <%= ENV['OPUS_UA_BACKEND_STG_DATABASE_NAME'] %>
  encoding: utf8
  pool: 5
  port: 5432
  username: <%= ENV['OPUS_UA_BACKEND_STG_DATABASE_USERNAME'] %>
  password: <%= ENV['OPUS_UA_BACKEND_STG_DATABASE_PASSWORD'] %>

production:
  host: <%= ENV['OPUS_UA_BACKEND_PRD_DATABASE_HOST'] %>
  database: <%= ENV['OPUS_UA_BACKEND_PRD_DATABASE_NAME'] %>
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432
  username: <%= ENV['OPUS_UA_BACKEND_PRD_DATABASE_USERNAME'] %>
  password: <%= ENV['OPUS_UA_BACKEND_PRD_DATABASE_PASSWORD'] %>
